######################################################################
# Automatically generated by qmake (3.1) Wed Feb 21 19:42:22 2024
######################################################################

TEMPLATE = app
TARGET = blazar
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += main.cc
